#!/bin/bash

echo "🚀 Portfolio Deployment Setup"
echo "=============================="

echo ""
echo "📋 Backend Deployment (Render)"
echo "1. Go to https://dashboard.render.com"
echo "2. Create new Web Service"
echo "3. Connect your GitHub repo"
echo "4. Set Root Directory to: backend"
echo "5. Set Build Command to: npm install"
echo "6. Set Start Command to: node index.js"
echo ""

echo "📋 Frontend Deployment (Vercel)"
echo "1. Go to https://vercel.com"
echo "2. Import your GitHub repo"
echo "3. Set Root Directory to: frontend"
echo "4. Set Framework Preset to: Vite"
echo ""

echo "🔧 Environment Variables"
echo ""
echo "Backend (Render):"
echo "MONGODB_URI=your-mongodb-connection-string"
echo "JWT_SECRET=your-super-secret-jwt-key"
echo "EMAIL_USER=your-email@gmail.com"
echo "EMAIL_PASS=your-gmail-app-password"
echo "PORT=10000"
echo "NODE_ENV=production"
echo ""
echo "Frontend (Vercel):"
echo "VITE_API_URL=https://your-render-backend-url.onrender.com"
echo ""

echo "⚠️  Important Notes:"
echo "- Replace 'your-render-backend-url.onrender.com' with your actual Render URL"
echo "- Replace 'your-vercel-frontend-url.vercel.app' with your actual Vercel URL"
echo "- Images won't work on Render (use external hosting like Cloudinary)"
echo "- Update CORS origins in backend/index.js with your actual URLs"
echo ""

echo "🔍 Testing Commands:"
echo "Backend health: curl https://your-render-backend-url.onrender.com/api/health"
echo "Frontend: curl https://your-vercel-frontend-url.vercel.app"
echo ""

echo "📚 See DEPLOYMENT.md for detailed instructions" 